package main

import (
	"log"
	"os"
	"time"

	"fly-wireguard-vpn-proxy/internal/bootstrap"
	"fly-wireguard-vpn-proxy/internal/config"
)

func main() {
	cfg := config.Load()

	// Wait for config file to be generated by the WireGuard container
	waitForFile(cfg.PeerConfigPath(), 30*time.Second)

	server := bootstrap.NewServer(cfg)
	server.Listen()
}

func waitForFile(path string, timeout time.Duration) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(path); err == nil {
			return
		}
		time.Sleep(time.Second)
	}
	log.Printf("warning: config file %s not found after %s", path, timeout)
}